# The commented out lines show optional configuration with their default value.
# All key material should be replaced with secret values.

# public_url: "http://localhost:3003/"

[webserver]
# ip = "0.0.0.0"
# port = 3003

[issuer_key]
private_key = "MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQg+LWW20wO1X9D2gZigpxRUt0ihqd5b+XI8rWtStyvGLqhRANCAASSB4wyDOXa2MznZw8fRJkRx4Du0EoEDCSulvKC/26wqTNtY6JQDmRBzIbvloUMK28iiUkWsFUk1AUYLSTD3qOW"
certificate = "MIIBkDCCATagAwIBAgIUdgiQmHWNVDMlKZ8nUFvPATneLf4wCgYIKoZIzj0EAwIwDzENMAsGA1UEAwwEbXljYTAeFw0yMzA4MTAxNTEwNDBaFw0yNDA4MDkxNTEwNDBaMBExDzANBgNVBAMMBm15Y2VydDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABJIHjDIM5drYzOdnDx9EmRHHgO7QSgQMJK6W8oL/brCpM21jolAOZEHMhu+WhQwrbyKJSRawVSTUBRgtJMPeo5ajbjBsMAsGA1UdDwQEAwIHgDASBgNVHSUECzAJBgcogYxdBQECMAkGA1UdEwQCMAAwHQYDVR0OBBYEFP4laNhDRZzCZifb+Aq0p6UzS4G1MB8GA1UdIwQYMBaAFEo7rznKSKXDq26vLDI4DLJPSGMkMAoGCCqGSM49BAMCA0gAMEUCIQCIlBMlpYYfzNI187hGDHrx9JwYEnC8MuC2HV+CMRvMQwIgN2kRIoXmPHrIwy3GHWbomF9yoiw4ons6soGDUZ8gO9Y="

[digid]
# client_id = "37692967-0a74-4e91-85ec-a4250e7ad5e8"
# issuer_url = "https://localhost:8006/"
bsn_privkey = '{"kty":"RSA","alg":"RSA-OAEP","n":"xfmmVxzkfT61O7W2C5PsFEL2Hc3MzXIpPqoxqAB9EXbIRjkSlxNTCBEXlKebjlKwaJbIP7oDt9QSUvVWdI-M89MieCAE8zeVRGt0g92ThR-XyfcdyRe77lFpP7_7mHJGV9pzh506jnd1oATwWIGVMGaufdMeyGwxS_0QEtRVeQNy2mO5pJqhAXGiN-y9jT7abDbLVNJuZF7CUYN0h06ZvI03EfpkZ-sbOCTGtH5_6nZatfC0j-HT9omyMCUZgjPz1QZfkmQ1Okq4MQse81-guYT1tBqyixkABAJ-DPZ2NobRztcuGJe-J66SUgzb9jMS92ri0LlzEckxxI2khd9Dlw","e":"AQAB","d":"hCbQrYfA0gXg7nmuim30gdXs-hodYuqYs5biTLX-xoCW0aFZUnV40IKwTe_P-6Ig1cAI7dkakERE8xGH44jLWxsOAEfHZh8tSZ29CiUHSy66oPuO62Qnc77uVbqulKV7ZTuSMO14YA9H-kgxs7LURpnUUnNyMfFeus2zRA5u-7Zv3qYSYpns5PenuUCW_tt00Tgl3BdsFEhx4HTic72B6Lx6LoK-yVCxs3kDJjeKZA6XxMnv0PhSaFoe9qwTN0amX2I8CFGEwbicvOblMniX-nk02o6O7wQhLq9m-6sDqS59iSiWIBlMUeYGxsBnf5_3V7r3V1BpLMT_gNxG4eybWQ","p":"6UiAYF2Mn6h12PANf0R2Zi3MglZwHhz0S3nEzD4fRLwJX-dFOzAvAbgBsX1J6RDW9xEoJdL4uAXIiqxDS7uSdp7gL2kjIZFbF0MOXwAqUE2Mdn6KWymT601JJ_gdJAPyv9xuWkKHl9nVihZTSdY8ZisczoDH8fPuKyuPSZ_H4XU","q":"2UD1Jlna1X6eigXkDVNF0Fp_kVmkRMCpqD6WEdHpwv3YJHa2Lu9BzVgGQMx5yJlOJLj61TxH3BlQ-RIF1A2ISY6mENPEd62QDEpHVi6SCKSQCjKKuIAZ5Ev7sS0sy6ayA_yLTIgyN25mRJoho2Y3ydqrX-kR1TZTsFwrwsv-w1s","dp":"BebZqJZ1Sky-voBENyYKQMeD1wBM0dY1r_siqXAg5mJDcnOtYrPzXH3FPTJIPmc4qQN8Gojd1fn_etKk2TOjnvCiB1EHnH_K6CnAIVMlvuZXWWAWK_w_S8KmySYTxqd66rOu7wWj3ImcR2QNM18CJCuPDQJhDJP5QIpXk6tBKUk","dq":"eiq58E_067shAbJgVFHwX0KUm7KR2guRG8fd8bVdw0WlZpPOzMPD9-m40nVpQjFbLPFMM96K9izSSM0ms-DMM7jgj3PV9gqGhzK5vK_BdNS9Hs7fDPMUHDnSFga2OurJDc7UsjugKWWOYqNdqRnQ41RwrCVO3tuG4hRik07NOyM","qi":"QtdcLTBnYqIQtFCE4HkXEcGrGkcJE5zw6PNcCHlc4997UAmwY8cI5q0baDC9ZZETu6E5oXd8eS5Uy6EZwlEm7yAUuMtwpxYH2hQov-N2HU1kfa7uJt-S4JHSL2GBpMH0VX5Cfoq9aT-ZdC4CInttfiNHXWHK23dEFWD3Z039_h8"}'

[[mock_data]]
[mock_data.person]
bsn = "999991772"
given_name = "Willeke Liselotte"
family_name = "De Bruijn"
family_name_birth = "Molenaar"
gender = "Female"
birth_date = "1997-05-10"
age_over_18 = true
birth_country = "NL"
birth_city = "Delft"
nationality = "NL"

[mock_data.resident]
street = "Turfmarkt"
house_number = "147"
postal_code = "2511 DP"
city = "Den Haag"
