apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: db-cluster-pi
spec:
  resources:
    requests:
      memory: "256Mi"
      cpu: "0.5"
    limits:
      memory: "256Mi"
      cpu: "0.5"
  storage:
    size: 1Gi
  walStorage:
    size: 1Gi

  postgresql:
    parameters:
      shared_buffers: "256MB"
