apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: db-cluster-pi
spec:
  imageName: SSSS/ghcr-io-proxy/cloudnative-pg/postgresql:15.3
  instances: 2

  inheritedMetadata:
    labels:
      app: pid-issuer-database
      group: nl-wallet-db
      tier: zeer-vertrouwd
      egress-frontoffice-policy: allow

  resources:
    requests:
      memory: "256Mi"
      cpu: "0.5"
    limits:
      memory: "256Mi"
      cpu: "0.5"

  affinity:
    enablePodAntiAffinity: true
    podAntiAffinityType: preferred
    topologyKey: kubernetes.io/hostname

  primaryUpdateStrategy: unsupervised

  enableSuperuserAccess: true

  storage:
    size: 2Gi

  bootstrap:
    initdb:
      database: pid_issuer
      owner: pid-issuer-user

  walStorage:
    size: 2Gi
