apiVersion: apps/v1
kind: Deployment
metadata:
  name: brpproxy
  labels:
    app: haal-centraal-brp-bevragen-api
spec:
  replicas: 2
  selector:
    matchLabels:
      name: brpproxy
  template:
    metadata:
      labels:
        name: brpproxy
        tier: vertrouwd
        gba-in-zeer-vertrouwd: allow
    spec:
      containers:
        - name: brpproxy
          image: $HARBOR_REGISTRY/ghcr-io-proxy/brp-api/haal-centraal-brp-bevragen-proxy:2.1.2
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Release"
            - name: ASPNETCORE_URLS
              value: "http://+:5000"
            - name: Routes__0__DownstreamScheme
              value: "http"
            - name: Routes__0__DownstreamHostAndPorts__0__Host
              value: "gba-hc-converter"
            - name: Routes__0__DownstreamHostAndPorts__0__Port
              value: "3006"
          ports:
            - name: http-brpproxy
              containerPort: 5000
