apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: preloaded-gba-v-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: encrypted-csi
