apiVersion: apps/v1
kind: Deployment
metadata:
  name: gbamock
  labels:
    app: haal-centraal-brp-bevragen-api
spec:
  replicas: 2
  selector:
    matchLabels:
      name: gbamock
  template:
    metadata:
      labels:
        name: gbamock
        tier: vertrouwd
    spec:
      containers:
        - name: gbamock
          image: $HARBOR_REGISTRY/ghcr-io-proxy/brp-api/haal-centraal-brp-bevragen-gba-mock:latest
          volumeMounts:
            - name: testdata
              mountPath: /app/Data/test-data.json
              subPath: test-data.json
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Release
            - name: ASPNETCORE_URLS
              value: http://+:5010
          ports:
            - name: http
              containerPort: 5010
      volumes:
        - name: testdata
          configMap:
            name: nl-wallet-gbav-testdata
