## Service account with persistent token for MacOS runner to get secrets
apiVersion: v1
kind: ServiceAccount
metadata:
  name: macos-runner-service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: macos-runner-secret-reader-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["nl-wallet-fastlane-match", "nl-wallet-core-env-file"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: macos-runner-secret-role-binding
subjects:
- kind: ServiceAccount
  name: macos-runner-service-account
roleRef:
  kind: Role
  name: macos-runner-secret-reader-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
metadata:
  name: macos-runner-service-account-token
  annotations:
    kubernetes.io/service-account.name: macos-runner-service-account
type: kubernetes.io/service-account-token