apiVersion: batch/v1
kind: Job
metadata:
  name: mrp-wallet-server-migrations-$CI_COMMIT_SHORT_SHA
  labels:
    app: mrp-wallet-server-migrations
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        tier: zeer-vertrouwd
    spec:
      imagePullSecrets:
        - name: harbor-puller
      containers:
        - name: mrp-wallet-server-migrations
          image: $WALLET_SERVER_MIGRATION_IMAGE
          args: ["fresh"]
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-cluster-mrp-app
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-cluster-mrp-app
                  key: password
            - name: DATABASE_URL
              value: "postgres://$(DB_USERNAME):$(DB_PASSWORD)@db-cluster-mrp-rw:5432/wallet_server"
      restartPolicy: Never
