apiVersion: v1
kind: Service
metadata:
  name: pid-issuer
  labels:
    service: pid-issuer
spec:
  selector:
    app: pid-issuer
    tier: vertrouwd
  ports:
    - name: pid-issuer-http
      port: 3007
      targetPort: pid-issuer-port
      protocol: TCP
