apiVersion: batch/v1
kind: Job
metadata:
  name: pid-issuer-migrations-$CI_COMMIT_SHORT_SHA
  labels:
    app: pid-issuer-migrations
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        tier: zeer-vertrouwd
    spec:
      imagePullSecrets:
        - name: harbor-puller
      containers:
        - name: pid-issuer-migrations
          image: $PID_ISSUER_MIGRATION_IMAGE
          args: ["fresh"]
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-cluster-pi-app
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-cluster-pi-app
                  key: password
            - name: DATABASE_URL
              value: "postgres://$(DB_USERNAME):$(DB_PASSWORD)@db-cluster-pi-rw:5432/pid_issuer"
      restartPolicy: Never
