apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: wallet-provider-servicemonitor
spec:
  endpoints:
    - interval: 10s
      port: wallet-provider-health-http
  namespaceSelector:
    matchNames:
      - $K8S_NAMESPACE
  selector:
    matchLabels:
      service: wallet-provider
