apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
    name: db-cluster
spec:
    imageName: SSSS/ghcr-io-proxy/cloudnative-pg/postgresql:15.3
    instances: 2

    inheritedMetadata:
        labels:
            app: wallet-provider-database
            group: nl-wallet-db
            tier: zeer-vertrouwd
            egress-frontoffice-policy: allow

    postgresql:
        parameters:
            shared_buffers: "256MB"

    resources:
        requests:
            memory: "256Mi"
            cpu: "0.5"
        limits:
            memory: "256Mi"
            cpu: "0.5"

    affinity:
        enablePodAntiAffinity: true
        podAntiAffinityType: preferred
        topologyKey: kubernetes.io/hostname

    primaryUpdateStrategy: unsupervised

    enableSuperuserAccess: true

    storage:
        size: 10Gi

    bootstrap:
        initdb:
            database: wallet_provider
            owner: db-wallet-provider-user
            postInitApplicationSQLRefs:
                configMapRefs:
                    - key: init.sql
                      name: db-init-sql

    walStorage:
        size: 10Gi
